on:
  push:
    branches:
    - main

permissions:
      id-token: write
      contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    steps:



      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'

      - name: List files in the current directory
        run: |
          ls
           shell: /bin/bash


      - name: data-factory-deploy
        uses: Azure/data-factory-deploy-action@v1.2.0
        with:
          resourceGroupName: Tej_RG
          dataFactoryName: prodadfbytej
          armTemplateFile: ${{github.workspace}}/devadfbytej/ARMTemplateForFactory.json
          armTemplateParametersFile: ${{github.workspace}}/devadfbytej/ARMTemplateParametersForFactory.json
          additionalParameters: 'factoryName=prodadfbytej'
